
modLoader="javafml"
loaderVersion="[41,)"
license="https://www.mit.edu/~amini/LICENSE.md"
issueTrackerURL="https://github.com/bigreefer/TheMissingVillages/issues"
[[mods]]
modId="themissingvillages"
version="2.0.1-1.19"
displayName="The Missing Villages"
logoFile="themissingvillages.png"
credits="Bigreefer"
authors="Bigreefer"
description="Adds Jungle and Swamp Villages to Minecraft"
[[dependencies.themissingvillages]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.themissingvillages]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
